# To run locally: docker-compose up --build --abort-on-container-exit
version: "3.7"
services:
  scan-results:
    image: mockserver/mockserver:latest
    command: -logLevel ERROR
    logging:
        driver: none
    ports:
      - 1080:1080
    environment:
        MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
        MOCKSERVER_PROPERTY_FILE: /config/mockserverscanresults.properties
        MOCKSERVER_INITIALIZATION_JSON_PATH: /config/scanresultsmockserver.json
        MOCKSERVER_SERVER_PORT: 1080
    volumes:
        - type: bind
          source: .
          target: /config
  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379
volumes:
  pacts: